### ISSUE TITLE
Section "Setup Tools" is extremely slow and/or throws errors sometimes

### ISSUE THREAD

**Issue by froemken** [shivammathur/node-docker#6]
**Describe the bug**
Something weird happens while processing "Setup Tools" section. This process is extremely slow and sometimes it breaks with the message:

```
==> Setup Tools
| ✗ composer Could not download composer
[CI/PHP Unit and Functional Tests-2]   ❗  ::error::The process '/bin/bash' failed with exit code 1
[CI/PHP Unit and Functional Tests-2]   ❌  Failure - Set up PHP Version ${{ matrix.php }}
Error: exit with `FAILURE`: 1
```

Interesting: I don't have defined any tools:
```
      - name: Set up PHP Version ${{ matrix.php }}
        #uses: shivammathur/setup-php@v2
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, intl, mysql
          ini-values: memory_limit=1024M, max_execution_time=30
          coverage: none
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 18.04

**PHP versions**
7.2, 7.2, 7.4

**To Reproduce**
```
jobs:
  testing:
    runs-on: 'ubuntu-18.04'
    name: PHP Unit and Functional Tests
    strategy:
      fail-fast: true
      matrix:
        typo3: ['^9.5', '^10.4']
        php: ['7.2', '7.3', '7.4']
        include:
          # Reduce side effects while running functional tests
          - typo3: '^9.5'
            db-name: 'mysql_95'
          - typo3: '^10.4'
            db-name: 'mysql_104'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP Version ${{ matrix.php }}
        #uses: shivammathur/setup-php@v2
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, intl, mysql
          ini-values: memory_limit=1024M, max_execution_time=30
          coverage: none
          tools: composer:v1

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          composer require typo3/cms-extensionmanager:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      # Will only work, if you define an env file with act --env-file
      # act pull_request -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04 --env-file ~/htdocs/.env.act.ci
      # The env file must contain these typo3Database* vars
      - name: Functional Tests locally
        if: ${{ env.GITHUB_ACTOR == 'nektos/act' }}
        env:
          typo3DatabaseName: ${{ matrix.db-name }}
          COMPOSER_PROCESS_TIMEOUT: 600
        run: composer ci:tests:functional
```

**Expected behavior**
Do not install any tools or do the job behind "Setup Tools" much faster or without error

**Screenshots/Logs**
I have tried many things, but every docker logs [hash] is empty

**Additional context**
My executed command:
`act pull_request -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04 -vvv --env-file ~/htdocs/.env.act.ci`

**Are you willing to submit a PR?**
Currently no, as I'm new to act since today
